### ISSUE TITLE
Getting SSL error on Windows

### ISSUE THREAD

**Issue by rpavlik** [zendesk/zendesk_api_client_rb#206]
I'm using the Chocolatey packages `ruby`, `ruby2.devkit`, and have run

```
gem update --system
gem update
```

In my local project, I'm using Bundler. When trying to use the API, I either get no/nil/empty response, or this error (truncated stack trace):

```
C:\Users\Ryan\Desktop\zendesk-migrate>bundler exec ruby migrate-users.rb                                              
DL is deprecated, please use Fiddle                                                                                   
C:/tools/ruby215/lib/ruby/2.1.0/net/http.rb:920:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Faraday::SSLError)                                                           
        from C:/tools/ruby215/lib/ruby/2.1.0/net/http.rb:920:in `block in connect'                                    
        from C:/tools/ruby215/lib/ruby/2.1.0/timeout.rb:76:in `timeout'                                               
        from C:/tools/ruby215/lib/ruby/2.1.0/net/http.rb:920:in `connect'                                             
        from C:/tools/ruby215/lib/ruby/2.1.0/net/http.rb:863:in `do_start'                                            
        from C:/tools/ruby215/lib/ruby/2.1.0/net/http.rb:852:in `start'                                               
        from C:/tools/ruby215/lib/ruby/2.1.0/net/http.rb:1369:in `request'                                            
        from C:/tools/ruby215/lib/ruby/2.1.0/net/http.rb:1128:in `get'                                                
        from C:/Users/Ryan/Desktop/zendesk-migrate/vendor/bundle/ruby/2.1.0/gems/faraday-0.9.1/lib/faraday/adapter/net
_http.rb:80:in `perform_request'                                                                                      
        from C:/Users/Ryan/Desktop/zendesk-migrate/vendor/bundle/ruby/2.1.0/gems/faraday-0.9.1/lib/faraday/adapter/net
_http.rb:40:in `block in call'                                                                                        
        from C:/Users/Ryan/Desktop/zendesk-migrate/vendor/bundle/ruby/2.1.0/gems/faraday-0.9.1/lib/faraday/adapter/net
_http.rb:87:in `with_net_http_connection'                                                                             
```

The sample code here is just trying to pretty-print `current_user` from the client.

**Comment by rpavlik** [comment]
Note that this only happens with the default faraday adapter - using `excon` works.

**Comment by steved555** [comment]
Interesting. The default adapter is net/http, I believe. I don't have a windows machine, but perhaps this [stackoverflow link](https://stackoverflow.com/questions/23263121/ruby-ssl-with-twitter-failed-on-cert-openssl-issue-on-windows-7) might help?

If excon works for you, however, I would just use that.
