### ISSUE TITLE
undefined method `keys' for "You are being redirected to /password":String

### ISSUE THREAD

**Issue by jonathansimmons** [zendesk/zendesk_api_client_rb#235]
We use the newrelic gem in our delayed job system and a couple weeks ago we had a failed job with the following error: 

```
undefined method `keys' for "You are being redirected to /password":String
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/zendesk_api-1.7.1/lib/zendesk_api/sideloading.rb:22:in `set_includes'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/zendesk_api-1.7.1/lib/zendesk_api/actions.rb:112:in `block in find!'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/zendesk_api-1.7.1/lib/zendesk_api/actions.rb:110:in `tap'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/zendesk_api-1.7.1/lib/zendesk_api/actions.rb:110:in `find!'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/zendesk_api-1.7.1/lib/zendesk_api/actions.rb:119:in `find'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/zendesk_api-1.7.1/lib/zendesk_api/collection.rb:62:in `block (2 levels) in <class:Collection>'
/home/webapps/myapp/app/models/concerns/ticketable.rb:41:in `block in create_tickets'
/home/webapps/myapp/app/models/concerns/ticketable.rb:39:in `each'
/home/webapps/myapp/app/models/concerns/ticketable.rb:39:in `create_tickets'
(eval):3:in `block in create_tickets_with_newrelic_transaction_trace'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:353:in `perform_action_with_newrelic_trace'
(eval):2:in `create_tickets_with_newrelic_transaction_trace'
/home/webapps/myapp/lib/watchman/jobs/process_v1.rb:278:in `process_plugin_results'
(eval):3:in `block in process_plugin_results_with_newrelic_transaction_trace'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:353:in `perform_action_with_newrelic_trace'
(eval):2:in `process_plugin_results_with_newrelic_transaction_trace'
/home/webapps/myapp/lib/watchman/jobs/process_v1.rb:27:in `perform'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:94:in `block in invoke_job'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:91:in `invoke_job'
(eval):3:in `block in invoke_job_with_newrelic_transaction_trace'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.11.1.284/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:353:in `perform_action_with_newrelic_trace'
(eval):2:in `invoke_job_with_newrelic_transaction_trace'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block (2 levels) in run'
/usr/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
/usr/lib/ruby/2.1.0/timeout.rb:101:in `call'
/usr/lib/ruby/2.1.0/timeout.rb:101:in `timeout'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block in run'
/usr/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:203:in `run'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `block in reserve_and_run_one_job'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `reserve_and_run_one_job'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:187:in `block in work_off'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `times'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `work_off'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:150:in `block (4 levels) in start'
/usr/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:149:in `block (3 levels) in start'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:148:in `block (2 levels) in start'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `loop'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `block in start'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `call'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block in add'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:146:in `start'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:124:in `run'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:112:in `block in run_process'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application.rb:265:in `call'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application.rb:265:in `block in start_proc'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/daemonize.rb:84:in `call'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/daemonize.rb:84:in `call_as_daemon'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application.rb:269:in `start_proc'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/application.rb:295:in `start'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/controller.rb:56:in `run'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons.rb:193:in `block in run_proc'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/cmdline.rb:88:in `call'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons/cmdline.rb:88:in `catch_exceptions'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/daemons-1.2.2/lib/daemons.rb:192:in `run_proc'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:110:in `run_process'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:91:in `block in daemonize'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:89:in `times'
/home/webapps/myapp/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb:89:in `daemonize'
bin/delayed_job:5:in `<main>'
```

Not sure what it means but thought it was worth reporting at least. We've not seen it since.

**Comment by steved** [comment]
Unfortunately, an incident occurred during that time that affected token API requests for users without a  password set. Since it was not a valid JSON response, the client could not handle it properly. If a public postmortem is posted, I'll make sure to update here.
