### ISSUE TITLE
Undefinded method upload

### ISSUE THREAD

**Issue by dbbooke12** [zendesk/zendesk_api_client_rb#417]
Getting an undefined method when trying to upload file.

```
@ticket.comment = params[:comment]
uploaded_io = params[:ticket][:file]
 File.open(uploaded_io.original_filename, 'wb') do |file|
     @ticket.comment.uploads << file.write(uploaded_io.read)
end

@zendesk_ticket.update(ticket_update_params)
```

```
NoMethodError (undefined method `uploads' for "file":String):
  /Users/darrenbooker/Desktop/zen-support/app/controllers/zen_support/tickets_controller.rb:68:in `block (3 levels) in update'
  /Users/darrenbooker/Desktop/zen-support/app/controllers/zen_support/tickets_controller.rb:67:in `open'
  /Users/darrenbooker/Desktop/zen-support/app/controllers/zen_support/tickets_controller.rb:67:in `block (2 levels) in update'
  actionpack (4.2.5.1) lib/action_controller/metal/mime_responds.rb:217:in `respond_to'
  /Users/darrenbooker/Desktop/zen-support/app/controllers/zen_support/tickets_controller.rb:62:in `update'
  actionpack (4.2.5.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.5.1) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.5.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.5.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
  rails-observers (0.1.2) lib/rails/observers/action_controller/caching/sweeping.rb:73:in `around'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:455:in `public_send'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:455:in `block in make_lambda'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:312:in `block in halting'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:497:in `block in around'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.5.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.5.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.5.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.5.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.5.1) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.5.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.5.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.5.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.5.1) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.5.1) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.5.1) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.5.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.5.1) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.5.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.5.1) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.5.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:815:in `call'
  railties (4.2.5.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.5.1) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.5.1) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.2.5.1) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.5.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.5.1) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.5.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:815:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  turnout (2.3.1) lib/rack/turnout.rb:25:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  browser (1.1.0) lib/browser/middleware.rb:51:in `run_app'
  browser (1.1.0) lib/browser/middleware.rb:31:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/rack/developer_mode.rb:48:in `traced_call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.6) lib/warden/manager.rb:34:in `catch'
  warden (1.2.6) lib/warden/manager.rb:34:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.5) lib/rack/etag.rb:24:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.5) lib/rack/conditionalget.rb:38:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.5) lib/rack/head.rb:13:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  remotipart (1.2.1) lib/remotipart/middleware.rb:27:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.5) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.5) lib/rack/session/abstract/id.rb:220:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  activerecord (4.2.5.1) lib/active_record/query_cache.rb:36:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  activerecord (4.2.5.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  activerecord (4.2.5.1) lib/active_record/migration.rb:377:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  airbrake (5.4.1) lib/airbrake/rack/middleware.rb:22:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  railties (4.2.5.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5.1) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.5) lib/rack/methodoverride.rb:22:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.5) lib/rack/runtime.rb:18:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  activesupport (4.2.5.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.5) lib/rack/lock.rb:17:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/static.rb:116:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.5) lib/rack/sendfile.rb:113:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  railties (4.2.5.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.5.1) lib/rails/application.rb:165:in `call'
  newrelic_rpm (3.16.3.323) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.6.5) lib/rack/content_length.rb:15:in `call'
  puma (3.7.1) lib/puma/configuration.rb:232:in `call'
  puma (3.7.1) lib/puma/server.rb:578:in `handle_request'
  puma (3.7.1) lib/puma/server.rb:415:in `process_client'
  puma (3.7.1) lib/puma/server.rb:275:in `block in run'
  puma (3.7.1) lib/puma/thread_pool.rb:120:in `block in spawn_thread'


  Rendered /Users/darrenbooker/.rvm/gems/ruby-2.3.8/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (3.6ms)
  Rendered /Users/darrenbooker/.rvm/gems/ruby-2.3.8/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/templates/rescues/_trace.text.erb (0.7ms)
  Rendered /Users/darrenbooker/.rvm/gems/ruby-2.3.8/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.text.erb (0.8ms)
  Rendered /Users/darrenbooker/.rvm/gems/ruby-2.3.8/gems/actionpack-4.2.5.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.text.erb (116.9ms)

```

**Comment by nogates** [comment]
Hello @dbbooke12 !

Sorry, but it's a bit unclear to me how your code works :)
On line 1 of you example, you are passing the comment param to the `@ticket` instance variable, but on the last line, you are calling the update method on the `@zendesk_ticket` instance variable...?

Could you please double check you are calling `update` on the right variable?

**Comment by dbbooke12** [comment]
Oh sorry for the confusion aha! Let me post the whole code 
Well I see the gem uses faraday right so we can't attach files from string of content. We have to use File or Tempfile? 

Trying to attach a file to a comment on an existing ticket

```
def update
      respond_to do |format|
        format.js do
          # don't save over comment, just use the field for validation
          @ticket.comment = params[:comment]
          @ticket.comment.uploads << File.open("test.txt")
          @zendesk_ticket.update(ticket_update_params)
          if @ticket.valid? && @zendesk_ticket.save! && @ticket.update(updated_at: Time.now)
            flash.now[:success] = "Your help request was successfully updated.\n
            Your support ticket number is ##{@zendesk_ticket.id}.\n\n
            You should receive a confirmation email shortly.\n\n
            Thank you!"
          else
            flash.now[:error] = if @ticket.errors.present?
              @ticket.errors.full_messages.join "\n"
            else
              'There was a problem sending out your request.'
            end
            render action: :edit
          end
        end
      end
    end


def ticket_update_params
      {
        comment: {
          body: params[:comment],
          author_id: zendesk_user.id
        }
      }
    end

private

def get_ticket
      @zendesk_ticket = ZendeskAPI::Ticket.find!(
        zen_client,
        id: params[:id]
      )
      @ticket = ZenSupport::Ticket.find_by!(zendesk_id: params[:id])
    end
```

**Comment by nogates** [comment]
> Well I see the gem uses faraday right so we can't attach files from string of content. We have to use File or Tempfile?

Yeah, correct! You need to use the path or a File instance. See: https://github.com/zendesk/zendesk_api_client_rb#attaching-files

However, as far as I can see, you are calling the method `upload` on the `@ticket` instance variable... but the `@ticket` var is a `ZenSupport::Ticket` instance, not a `ZendeskAPI::Ticket`? So I think you are calling `upload` on the wrong instance

**Comment by dbbooke12** [comment]
Hey @nogates 
That worked perfectly. Everything went through but the attachment isn't showing up in zendesk?

```
Started PUT "/tickets/176" for 127.0.0.1 at 2019-12-11 20:15:44 -0800
Processing by ZenSupport::TicketsController#update as JS
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"GtYJjXyk4/4/0he728LfU/EcJ2qdXhpNwvIH4LHhR1hj+SSZEtC33eCwP5HCF59245deOAaiZsK7ksuCZKPLPg==", "comment"=>"dummy pdf", "commit"=>"Submit", "remotipart_submitted"=>"true", "X-Requested-With"=>"IFrame", "X-Http-Accept"=>"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript, */*; q=0.01", "ticket"=>{"file"=>#<ActionDispatch::Http::UploadedFile:0x00007fc9d72ec6f8 @tempfile=#<Tempfile:/var/folders/44/ft_zkkq11m93z2vxvq01sg2r0000gn/T/RackMultipart20191211-38145-12zruiy.pdf>, @original_filename="dummy.pdf", @content_type="application/pdf", @headers="Content-Disposition: form-data; name=\"ticket[file]\"; filename=\"dummy.pdf\"\r\nContent-Type: application/pdf\r\n">}, "id"=>"176"}
  User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 24]]
  ZenSupport::Ticket Load (0.3ms)  SELECT  "zen_support_tickets".* FROM "zen_support_tickets" WHERE "zen_support_tickets"."zendesk_id" = $1 LIMIT 1  [["zendesk_id", 176]]
  UserReference Load (0.2ms)  SELECT  "user_references".* FROM "user_references" WHERE "user_references"."id" = $1 LIMIT 1  [["id", 4]]
  DataEncryptionKey Load (0.4ms)  SELECT  "data_encryption_keys".* FROM "data_encryption_keys" WHERE "data_encryption_keys"."id" = $1 LIMIT 1  [["id", 1]]
   (0.3ms)  BEGIN
  SQL (0.3ms)  UPDATE "zen_support_tickets" SET "updated_at" = $1 WHERE "zen_support_tickets"."id" = $2  [["updated_at", "2019-12-12 04:15:48.099277"], ["id", 2]]
   (0.4ms)  COMMIT
  Rendered layouts/_standard_flash.html.haml (5.5ms)
  Rendered /Users/darrenbooker/Desktop/zen-support/app/views/zen_support/tickets/update.js.haml (9.7ms)
Completed 200 OK in 3868ms (Views: 72.5ms | ActiveRecord: 2.3ms)
```

**Comment by nogates** [comment]
@dbbooke12 You need to pass the actual path of the file or an instance of the file to the `uploads` method... but if you are doing something like

```
    File.open(uploaded_io.original_filename, 'wb') do |file|
       @zendesk-ticket.comment.uploads << file.write(uploaded_io.read)
    end
``` 

That's not gonna work, because you are passing the output of `file.write(uploaded_io.read)` which is the number of bits that were written into the filesystem

You would need to do pass the actual path:

```
@zendesk_ticket.comment.uploads << uploaded_io.original_filename
```

**Comment by dbbooke12** [comment]
Passing in the Path just like 

`@zendesk_ticket.comment.uploads << uploaded_io.original_filename`

does throw any errors but still not showing up

In the logs it's showing 
`"file"=>#<ActionDispatch::Http::UploadedFile:0x00007fc9d72ec6f8 @tempfile=#<Tempfile:/var/folders/44/ft_zkkq11m93z2vxvq01sg2r0000gn/T/RackMultipart20191211-38145-12zruiy.pdf>`

**Comment by nogates** [comment]
@dbbooke12 You need to work out the actual path of the file. Maybe the `original_filename` only returns the actual filename? I don't know what type of object he `uploaded_io` is, but I guess it will have a method that you can use to return the whole path?

**Comment by ecoologic** [comment]
Closing as inactive. I assume the user found a solution applying the latest suggestion.
