### ISSUE TITLE
Cannot call collection methods that return JobStatus

### ISSUE THREAD

**Issue by steved** [zendesk/zendesk_api_client_rb#94]
Methods like Ticket#destroy_many cannot be called from Collection because they return a single JobStatus instance.

```
I, [2013-06-03T10:42:24.254471 #70348]  INFO -- : delete https://abc123.zendesk.com/api/v2/tickets/destroy_many?ids=1%2C2%2C3%2C4
{"job_status"=>{"id"=>"6f05c8e0ae57013013ad782bcb36ca73", "url"=>"https://abc123.zendesk.com/api/v2/job_statuses/6f05c8e0ae57013013ad782bcb36ca73.json", "total"=>nil, "progress"=>nil, "status"=>"queued", "message"=>nil, "results"=>nil}}
/Users/stevendavidovitz/src/zendesk_api_client_rb/lib/zendesk_api/collection.rb:354:in `handle_response': undefined method `map' for nil:NilClass (NoMethodError)
        from /Users/stevendavidovitz/src/zendesk_api_client_rb/lib/zendesk_api/collection.rb:149:in `fetch!'
        from example.rb:42:in `<main>'
```

**Comment by steved** [comment]
Implemented by #252
